name: go-lambda-template-ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Lint Go code
        run: |
          go install golang.org/x/lint/golint@latest
          golint ./src/...

      - name: Format Go code
        run: gofmt -l -s -w ./src

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Check Terraform formatting
        run: terraform fmt terraform/ -check

      - name: Install yamllint and mdformat
        run: pip install yamllint mdformat

      - name: Lint YAML files
        run: yamllint .

      - name: Format Markdown files (check only)
        run: mdformat --check .
